#!/bin/bash

while [[ $# -gt 0 ]]; do
  case $1 in
    -p|--project-name)
      name="$2"
      shift
      shift
      ;;
  esac
done

if [ -z "$name" ]
then
  exit 1

else
  openssl req -newkey rsa:4096 -nodes -keyout "$name-azurerm.key" -out "$name-azurerm.csr" && \
  openssl x509 -signkey "$name-azurerm.key" -in "$name-azurerm.csr" -req -days 365 -out "$name-azurerm.crt" && \
  openssl pkcs12 -export -out "$name-azurerm.pfx" -inkey "$name-azurerm.key" -in "$name-azurerm.crt" && \
  exit 0

fi

